CREATE DATABASE IF NOT EXISTS GIT_TEST_DB;

CREATE SCHEMA IF NOT EXISTS GIT_TEST_DB.DEMO;

CREATE OR REPLACE TABLE GIT_TEST_DB.DEMO.CUSTOMERS
(
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    COUNTRY VARCHAR
);

INSERT INTO GIT_TEST_DB.DEMO.CUSTOMERS
    (CUSTOMER_ID, CUSTOMER_NAME, COUNTRY)
VALUES
    (1, 'Ali', 'Azerbaijan'),
    (2, 'Sara', 'Germany'),
    (3, 'John', 'United Kingdom');

INSERT INTO GIT_TEST_DB.DEMO.CUSTOMERS
    (CUSTOMER_ID, CUSTOMER_NAME, COUNTRY)
VALUES
    (4, 'Daniel', 'Korea'),

SELECT *
FROM GIT_TEST_DB.DEMO.CUSTOMERS;
